name: Foundry Testing
on:
  push:
    branches:
      - "**"

concurrency:
  group: "Foundry Testing-${{ github.ref }}"
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ci
  WORKFLOW_NAME: Foundry Test on ${{ github.ref }}

jobs:
  check:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd hw0
          forge --version
          forge build --sizes

      - name: Run Forge tests
        run: |
          cd hw0
          forge test -vvv
